// Exercise the packaged Electron renderer with synthetic complete files, no Gerrit.
// Build first, then on Linux: xvfb-run -a node_modules/.bin/electron --no-sandbox test/review-ui.cjs
const { app, BrowserWindow, nativeTheme } = require('electron')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const taskData = fs.mkdtempSync(path.join(os.tmpdir(), 'gerrit-review-ui-'))
app.setPath('userData', taskData)
app.disableHardwareAcceleration()
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
const timeout = setTimeout(() => { console.error('Review UI test timed out'); app.exit(2) }, 90000)
app.whenReady().then(async () => {
  nativeTheme.themeSource = 'light'
  const win = new BrowserWindow({ width: 1440, height: 960, useContentSize: true, show: true, frame: false,
    webPreferences: { contextIsolation: true, sandbox: false, preload: path.join(__dirname, 'fixtures/local-review-preload.cjs') } })
  const errors = []
  win.webContents.on('console-message', (details) => {
    if (details.level === 'error' || /Could not create web worker|Falling back to loading web worker/.test(details.message)) errors.push(details.message)
  })
  const run = (script) => win.webContents.executeJavaScript(script).catch((error) => { console.error('Failed renderer check:', script, errors); throw error })
  async function until(script, label) {
    for (let i = 0; i < 150; i++) { if (await run(script)) return; await delay(100) }
    await screenshot('review-test-failure')
    console.error(await run(`({focus:document.activeElement?.outerHTML, lines:document.querySelector('.review-editor .view-lines')?.innerHTML.slice(0,2000), preferences:localStorage.getItem('local-review-diff-preferences')})`))
    throw new Error(`Timed out: ${label}`)
  }
  async function click(selector) { await run(`document.querySelector(${JSON.stringify(selector)}).click()`); await delay(150) }
  async function press(keyCode, modifiers = []) {
    win.webContents.sendInputEvent({ type: 'keyDown', keyCode, modifiers })
    win.webContents.sendInputEvent({ type: 'keyUp', keyCode, modifiers })
    await delay(80)
  }
  const selector = '.modified-in-monaco-diff-editor'
  const barSelector = selector + ' .scrollbar.vertical .slider'
  const firstLine = () => run(`document.querySelector('${selector} .view-lines').textContent`)
  const bar = () => run(`document.querySelector('${barSelector}').getBoundingClientRect().toJSON()`)
  async function screenshot(name) {
    if (!process.env.REVIEW_SCREENSHOTS) return
    const dir = name === 'review-test-failure' ? os.tmpdir() : path.join(__dirname, '../docs/screenshots/local-review')
    fs.mkdirSync(dir, { recursive: true })
    const previousTheme = nativeTheme.themeSource
    for (const theme of ['light', 'dark']) {
      nativeTheme.themeSource = theme
      await delay(250)
      fs.writeFileSync(path.join(dir, name + '-' + theme + '.png'), (await win.webContents.capturePage()).toPNG())
    }
    nativeTheme.themeSource = previousTheme
    await delay(150)
  }
  await win.loadFile(path.join(__dirname, '../out/renderer/index.html'))
  await until(`Boolean(document.querySelector('.review-main'))`, 'review button')
  await click('button[aria-label="Settings"]')
  await run(`Array.from(document.querySelectorAll('.section-nav button')).find(b => b.textContent === 'Beta').click()`)
  await screenshot('beta-settings')
  assert.equal(await run(`document.querySelector('.section-body input[type="checkbox"]').checked`), false)
  await click('.section-body input[type="checkbox"]')
  await click('button[aria-label="Settings"]')
  await run(`(() => { const spacer = document.createElement('div'); spacer.id = 'background-overflow-fixture'; spacer.style.height = '2000px'; document.body.append(spacer); })()`)
  const oldOverflow = await run(`({ html: document.documentElement.style.overflow, body: document.body.style.overflow })`)
  await click('.review-main')
  await until(`Boolean(document.querySelector('${barSelector}')) && document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, 'editor and worker diff')
  await until(`document.querySelectorAll('.review-editor .view-zones > div').length < 300`, 'fit to screen keeps alignment spacers bounded')
  assert.deepEqual(errors, [], 'workers, styles and language modules load under the packaged CSP')
  assert.equal(await run(`document.documentElement.clientWidth === window.innerWidth && document.documentElement.style.overflow === 'hidden' && document.body.style.overflow === 'hidden'`), true, 'background scrollbar is hidden')
  assert.equal(await run(`document.querySelector('.local-review').scrollHeight <= document.querySelector('.local-review').clientHeight + 1`), true, 'dialog has no redundant outer scrolling')
  await screenshot('full-file-review')
  win.focus()
  win.webContents.focus()
  await delay(250)
  const initial = await bar()
  const initialText = await firstLine()
  const box = await run(`document.querySelector('${selector}').getBoundingClientRect().toJSON()`)
  win.webContents.sendInputEvent({ type: 'mouseMove', x: Math.round(box.x + box.width / 2), y: Math.round(box.y + 200) })
  win.webContents.sendInputEvent({ type: 'mouseWheel', x: Math.round(box.x + box.width / 2), y: Math.round(box.y + 200), deltaY: -20000, deltaX: 0, canScroll: true, wheelTicksY: -166, hasPreciseScrollingDeltas: true })
  await until(`document.querySelector('${barSelector}').getBoundingClientRect().y > ${initial.y + 0.01}`, 'wheel moves scrollbar thumb')
  assert.notEqual(await firstLine(), initialText, 'wheel changes visible text')
  await delay(100)
  const afterWheel = await bar()
  const afterWheelText = await firstLine()
  // Drag the actual scrollbar, rather than mutating scrollTop in JavaScript.
  const x = Math.round(afterWheel.x + afterWheel.width / 2)
  const y = Math.round(afterWheel.y + afterWheel.height / 2)
  win.webContents.sendInputEvent({ type: 'mouseDown', x, y, button: 'left', clickCount: 1 })
  await delay(50)
  win.webContents.sendInputEvent({ type: 'mouseMove', x, y: y + 260, button: 'left', modifiers: ['leftbuttondown'] })
  await delay(50)
  win.webContents.sendInputEvent({ type: 'mouseUp', x, y: y + 260, button: 'left', clickCount: 1 })
  await until(`document.querySelector('${barSelector}').getBoundingClientRect().y > ${afterWheel.y + 100}`, 'drag moves scrollbar thumb')
  assert.notEqual(await firstLine(), afterWheelText, 'drag changes visible text')
  const positions = await run(`Array.from(document.querySelectorAll('.review-editor .scrollbar.vertical .slider')).map(el => el.getBoundingClientRect().y)`)
  assert.ok(Math.abs(positions[0] - positions[1]) < 2, 'both sides stay vertically synchronized')
  // Editor keyboard navigation goes to the end of the complete in-memory model.
  win.webContents.sendInputEvent({ type: 'mouseDown', x: Math.round(box.x + 180), y: Math.round(box.y + 180), button: 'left', clickCount: 1 })
  win.webContents.sendInputEvent({ type: 'mouseUp', x: Math.round(box.x + 180), y: Math.round(box.y + 180), button: 'left', clickCount: 1 })
  await delay(100)
  win.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'End', modifiers: ['control'] })
  win.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'End', modifiers: ['control'] })
  await until(`document.querySelector('${selector} .view-lines')?.textContent.replaceAll('\u00a0', ' ').includes('End of delivery fixtures')`, 'Ctrl+End reaches full-file end')
  await screenshot('large-file-navigation')
  // Gerrit navigation is handled before Monaco consumes printable keys.
  await press('.')
  assert.ok(await run(`Number(document.querySelector('${selector} .line-numbers.active-line-number')?.textContent) > 99000`), 'dot moves the cursor to visible code')
  await press('Home', ['control'])
  const activeLine = () => run(`Number(document.querySelector('${selector} .line-numbers.active-line-number')?.textContent)`)
  assert.equal(await activeLine(), 1)
  await press('J')
  assert.equal(await activeLine(), 2, 'j moves one line')
  await press('K')
  assert.equal(await activeLine(), 1, 'k moves one line')
  await press('Down')
  assert.equal(await activeLine(), 2, 'Down moves one line')
  await press('Up')
  assert.equal(await activeLine(), 1, 'Up moves one line')
  await press('N')
  const firstChunk = await activeLine()
  assert.ok(firstChunk > 1)
  await press('N')
  assert.ok(await activeLine() > firstChunk, 'n moves to the next chunk')
  await press('P')
  assert.equal(await activeLine(), firstChunk, 'p moves to previous chunk')
  await press('Left', ['shift'])
  assert.equal(await run(`Boolean(document.activeElement.closest('.original-in-monaco-diff-editor'))`), true, 'Shift+Left selects original pane')
  await press('Right', ['shift'])
  assert.equal(await run(`Boolean(document.activeElement.closest('${selector}'))`), true, 'Shift+Right selects modified pane')
  await press('M')
  await until(`Boolean(document.querySelector('.review-side-head.unified'))`, 'm switches to unified diff')
  await press('M')
  await until(`!document.querySelector('.review-side-head.unified')`, 'm restores side-by-side')
  await press('?', ['shift'])
  await until(`Boolean(document.querySelector('.review-shortcuts[open]'))`, 'shortcut help')
  await screenshot('keyboard-shortcuts')
  await press('Escape')
  await until(`!document.querySelector('.review-shortcuts') && Boolean(document.querySelector('.local-review[open]'))`, 'Escape closes only help')
  await press('F')
  assert.equal(await run(`document.activeElement.getAttribute('aria-current')`), 'true', 'f focuses selected file')
  await press('J')
  assert.equal(await run(`document.activeElement.textContent`), 'types.ts', 'j navigates file list')
  await press('Enter')
  await until(`document.querySelector('.review-side-head')?.textContent.includes('types.ts') && document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, 'Enter opens file')
  await press('[')
  await until(`document.querySelector('.review-side-head')?.textContent.includes('batch-scheduler.ts') && document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, '[ opens previous cached file')
  await press(']')
  await until(`document.querySelector('.review-side-head')?.textContent.includes('types.ts') && document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, '] opens next cached file')
  await press('[')
  await until(`document.querySelector('.review-side-head')?.textContent.includes('batch-scheduler.ts') && document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, 'return to cached file')
  await click('button[data-review-find]')
  await until(`Boolean(document.querySelector('${selector} .find-widget.visible'))`, 'editor find widget')
  // A delayed tooltip over search controls must not intercept actual mouse clicks.
  await delay(350) // Let Monaco's find-widget entrance animation finish.
  const closeSearch = selector + ' .find-widget .button.codicon-widget-close'
  const closeBox = await run(`document.querySelector('${closeSearch}').getBoundingClientRect().toJSON()`)
  const closeX = Math.round(closeBox.x + closeBox.width / 2)
  const closeY = Math.round(closeBox.y + closeBox.height / 2)
  win.webContents.sendInputEvent({ type: 'mouseMove', x: closeX, y: closeY })
  await until(`Boolean(document.querySelector('.review-editor .workbench-hover'))`, 'search button tooltip shown')
  const tooltip = await run(`document.querySelector('.review-editor .workbench-hover').getBoundingClientRect().toJSON()`)
  assert.ok(tooltip.width > 0 && tooltip.height > 0, 'tooltip is rendered')
  assert.equal(await run(`getComputedStyle(document.querySelector('.review-editor .workbench-hover')).pointerEvents`), 'none', 'search hints are informational')
  // Recreate the reported overlap, independently of the native window size.
  await run(`(() => { const view = document.querySelector('.review-editor .workbench-hover').closest('.context-view'); Object.assign(view.style, {position:'fixed',left:'${closeX - 8}px',top:'${closeY - 8}px',zIndex:'10000'}); })()`)
  assert.equal(await run(`Boolean(document.elementFromPoint(${closeX}, ${closeY})?.closest('${closeSearch}'))`), true, 'tooltip does not cover the close control hit target')
  win.webContents.sendInputEvent({ type: 'mouseDown', x: closeX, y: closeY, button: 'left', clickCount: 1 })
  win.webContents.sendInputEvent({ type: 'mouseUp', x: closeX, y: closeY, button: 'left', clickCount: 1 })
  await until(`!document.querySelector('${selector} .find-widget.visible')`, 'mouse click closes search while tooltip is present')
  win.webContents.sendInputEvent({ type: 'mouseMove', x: 100, y: 100 })
  await click('button[data-review-find]')
  await until(`Boolean(document.querySelector('${selector} .find-widget.visible'))`, 'search reopens normally')
  for (const letter of ['j', 'n', 'u']) {
    await press(letter.toUpperCase())
    win.webContents.sendInputEvent({ type: 'char', keyCode: letter })
    await delay(50)
  }
  assert.equal(await run(`(document.querySelector('${selector} .find-widget input')?.value ?? document.querySelector('${selector} .find-widget textarea')?.value ?? document.querySelector('${selector} .find-widget [role=\"textbox\"]')?.textContent)`), 'jnu', 'navigation keys remain text in the search box')
  assert.equal(await run(`Boolean(document.querySelector('.local-review[open]'))`), true, 'typing u does not close review')
  // Returning to a previously loaded file uses the session cache.
  await click('[data-review-path="src/telemetry/types.ts"]')
  await until(`document.querySelector('.review-side-head')?.textContent.includes('types.ts') && document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, 'second file')
  await click('[data-review-path="src/telemetry/batch-scheduler.ts"]')
  await until(`document.querySelector('.review-side-head')?.textContent.includes('batch-scheduler.ts') && document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, 'cached file')
  // Gerrit-style preferences are transactional and keep source fully loaded.
  await press('Home', ['control'])
  const requestCountBeforePreferences = (await run('window.api.fixtureStats()')).requests
  await click('button[data-review-preferences]')
  await until(`Boolean(document.querySelector('.review-preferences[open]'))`, 'diff preferences')
  await screenshot('diff-preferences')
  assert.equal(await run(`document.querySelector('.review-preferences select').value`), '-1', 'whole-file default')
  async function preference(label, value) {
    await run(`(() => {
      const field = Array.from(document.querySelectorAll('.review-preference-fields label')).find(el => el.childNodes[0].textContent === ${JSON.stringify(label)}).querySelector('input,select');
      if (field.type === 'checkbox') { if (field.checked !== ${JSON.stringify(value)}) field.click(); }
      else { Object.getOwnPropertyDescriptor(field.tagName === 'SELECT' ? HTMLSelectElement.prototype : HTMLInputElement.prototype, 'value').set.call(field, ${JSON.stringify(String(value))}); field.dispatchEvent(new Event(field.tagName === 'SELECT' ? 'change' : 'input', {bubbles:true})); }
    })()`)
    await delay(40)
  }
  await preference('Font size', 18)
  await press('Escape')
  assert.equal(await run(`Boolean(document.querySelector('.local-review[open]')) && !document.querySelector('.review-preferences')`), true, 'Escape closes only preferences')
  assert.equal(await run(`localStorage.getItem('local-review-diff-preferences')`), null, 'cancel discards edits')
  await click('button[data-review-preferences]')
  await preference('Fit to screen', false)
  await preference('Diff width', 500)
  await preference('Font size', 18)
  await preference('Tab width', 8)
  await preference('Show tabs', true)
  await preference('Show trailing whitespace', false)
  await preference('Syntax highlighting', false)
  await preference('Ignore Whitespace', 'IGNORE_ALL')
  await preference('Context', 10)
  await click('.review-preferences button[type=submit]')
  await until(`!document.querySelector('.review-preferences') && Boolean(document.querySelector('.diff-hidden-lines-widget'))`, 'context limit applied')
  assert.equal(await run(`getComputedStyle(document.querySelector('${selector} .view-lines')).fontSize`), '18px', 'font size applied to real editor')
  await run(`document.querySelector('${selector} .native-edit-context, ${selector} .inputarea').focus()`)
  await press('Home', ['control'])
  const persisted = await run(`JSON.parse(localStorage.getItem('local-review-diff-preferences'))`)
  assert.deepEqual({context:persisted.context, font:persisted.fontSize, tabs:persisted.tabWidth, width:persisted.diffWidth, whitespace:persisted.ignoreWhitespace}, {context:10,font:18,tabs:8,width:500,whitespace:'IGNORE_ALL'})
  await screenshot('limited-context-review')
  // Restore whole-file context without any new content request. Ignore All
  // must suppress the whitespace-only first chunk in the actual editor.
  await click('button[data-review-preferences]')
  await preference('Context', -1)
  await click('.review-preferences button[type=submit]')
  await until(`!document.querySelector('.diff-hidden-lines-widget')`, 'whole file restored')
  await run(`document.querySelector('${selector} .native-edit-context, ${selector} .inputarea').focus()`)
  await press('Home', ['control'])
  await until(`Boolean(document.querySelector('.review-visible-tab'))`, 'visible tab marker')
  await press('N')
  assert.ok(await activeLine() > 10, 'Ignore All skips the whitespace-only chunk')
  assert.equal((await run('window.api.fixtureStats()')).requests, requestCountBeforePreferences, 'preferences are entirely local')
  // Test both selectors, source identity, and comparison-scoped session caching.
  async function comparisonSelect(label, value) {
    await run(`(() => {const el=document.querySelector('select[aria-label="${label}"]');el.value=${JSON.stringify(String(value))};el.dispatchEvent(new Event('change',{bubbles:true}));})()`)
    await until(`document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, 'selected comparison ready')
    await run(`document.querySelector('${selector} .native-edit-context, ${selector} .inputarea').focus()`)
    await press('Home', ['control'])
  }
  await comparisonSelect('Base patch set', 2)
  await until(`document.querySelector('${selector} .view-lines')?.textContent.replaceAll('\u00a0',' ').includes('Comparing 2 to patch set 3')`, 'new base content')
  await screenshot('patch-set-comparison')
  await comparisonSelect('Base patch set', 'base')
  assert.equal((await run('window.api.fixtureStats()')).requests, 3, 'returning to old comparison is cached')
  await until(`document.querySelector('${selector} .view-lines')?.textContent.replaceAll('\u00a0',' ').includes('Comparing base to patch set 3')`, 'cached comparison identity')
  await comparisonSelect('Compared patch set', 2)
  await until(`document.querySelector('${selector} .view-lines')?.textContent.replaceAll('\u00a0',' ').includes('Comparing base to patch set 2')`, 'new target content')
  // Reviewed is real revision-scoped state. Auto marking is explicitly enabled.
  assert.equal(await run(`document.querySelector('input[aria-label="File reviewed"]').checked`), false)
  await click('input[aria-label="File reviewed"]')
  await until(`document.querySelector('input[aria-label="File reviewed"]').checked`, 'manual reviewed write')
  await click('input[aria-label="File reviewed"]')
  await until(`!document.querySelector('input[aria-label="File reviewed"]').checked && !document.querySelector('input[aria-label="File reviewed"]').disabled`, 'manual reviewed clear')
  await click('button[data-review-preferences]')
  await preference('Automatically mark viewed files reviewed', true)
  await click('.review-preferences button[type=submit]')
  await until(`document.querySelector('input[aria-label="File reviewed"]').checked`, 'automatic reviewed write')
  await click('input[aria-label="File reviewed"]')
  await until(`!document.querySelector('input[aria-label="File reviewed"]').checked && !document.querySelector('input[aria-label="File reviewed"]').disabled`, 'manual clear overrides automatic marking for this visit')
  await delay(250)
  assert.equal(await run(`document.querySelector('input[aria-label="File reviewed"]').checked`), false)
  const flags = (await run('window.api.fixtureStats()')).reviewedWrites
  assert.deepEqual(flags.map(f => [f.link.patchSet,f.reviewed]), [[2,true],[2,false],[2,true],[2,false]])
  // The compact sidebar separates opening a file from its reviewed status.
  const beforeSidebar = (await run('window.api.fixtureStats()')).requests
  const selectedBeforeStatus = await run(`document.querySelector('[data-review-path][aria-current=true]').dataset.reviewPath`)
  await click('.review-file-row:nth-child(3) .review-status')
  await until(`document.querySelector('.review-files-heading').textContent.includes('1/2 reviewed')`, 'sidebar reviewed progress')
  assert.equal(await run(`document.querySelector('[data-review-path][aria-current=true]').dataset.reviewPath`), selectedBeforeStatus, 'status toggle keeps the current file open')
  assert.equal((await run('window.api.fixtureStats()')).requests, beforeSidebar, 'marking another file does not fetch its source')
  assert.equal(await run(`getComputedStyle(document.querySelector('.review-file-name')).fontSize`), '12px')
  assert.equal(await run(`document.querySelector('.review-file-row').getBoundingClientRect().height`), 24)
  assert.ok((await run(`document.querySelector('[data-review-path]').title`)).startsWith('src/telemetry/batch-scheduler.ts'), 'full path and change details stay available')
  const resizeBox = await run(`document.querySelector('.review-file-resize').getBoundingClientRect().toJSON()`)
  const resizeX = Math.round(resizeBox.x + resizeBox.width / 2), resizeY = Math.round(resizeBox.y + 100)
  win.webContents.sendInputEvent({type:'mouseDown',x:resizeX,y:resizeY,button:'left',clickCount:1})
  await delay(50)
  win.webContents.sendInputEvent({type:'mouseMove',x:resizeX+40,y:resizeY,modifiers:['leftbuttondown']})
  await delay(50)
  win.webContents.sendInputEvent({type:'mouseUp',x:resizeX+40,y:resizeY,button:'left',clickCount:1})
  await until(`Number(document.querySelector('.review-file-resize').getAttribute('aria-valuenow')) >= 225`, 'sidebar resizes with real mouse input')
  const pointerWidth = await run(`Number(document.querySelector('.review-file-resize').getAttribute('aria-valuenow'))`)
  await run(`document.querySelector('.review-file-resize').focus()`)
  await press('Left')
  assert.ok(await run(`Number(document.querySelector('.review-file-resize').getAttribute('aria-valuenow')) < ${pointerWidth}`), 'sidebar resizes with keyboard')
  await press('Left')
  await press('Left')
  await press('Left')
  await run(`document.querySelector('${selector} .native-edit-context, ${selector} .inputarea').focus()`)
  await screenshot('compact-file-list')
  await click('.review-files-filter input')
  assert.equal(await run(`document.querySelectorAll('[data-review-path]').length`), 1, 'unreviewed filter hides reviewed files')
  assert.equal(await run(`document.querySelector('.review-side-head').textContent.includes('batch-scheduler.ts')`), true, 'current filename stays visible')
  await click('.review-files-filter input')
  assert.equal(await run(`document.querySelectorAll('[data-review-path]').length`), 2, 'all-files view restores reviewed entries')
  const requests = await run('window.api.fixtureStats()')
  assert.equal(requests.requests, 4, 'two original files plus two new comparisons; all other navigation and preferences remain local')
  const rendered = await run(`document.querySelectorAll('.review-editor .view-line').length`)
  assert.ok(rendered < 300, 'the DOM remains bounded for 100k lines')
  await run(`document.querySelector('${selector} .native-edit-context, ${selector} .inputarea').focus()`); await press(','); await until(`Boolean(document.querySelector('.review-preferences[open]'))`, 'preferences shortcut'); await press('Escape')
  await run(`document.querySelector('${selector} .native-edit-context, ${selector} .inputarea').focus()`); await press('R'); await until(`document.querySelector('[aria-label="File reviewed"]').checked`, 'reviewed shortcut marks current file'); await press('R'); await until(`!document.querySelector('[aria-label="File reviewed"]').checked`, 'reviewed shortcut unmarks current file')
  await click('[aria-label="Mark unreviewed: src/telemetry/types.ts"]'); await run(`document.querySelector('${selector} .native-edit-context, ${selector} .inputarea').focus()`); await press('M', ['shift']); await until(`document.querySelector('[data-review-path="src/telemetry/types.ts"]').getAttribute('aria-current') === 'true' && document.querySelector('.review-editor')?.dataset.reviewReady === 'true'`, 'mark and next-unreviewed shortcut')
  await click('button[data-review-find]')
  await run(`document.querySelector('${selector} .native-edit-context, ${selector} .inputarea').focus()`)
  await press('U')
  await until(`!document.querySelector('.local-review')`, 'review closes cleanly')
  assert.deepEqual(await run(`({html:document.documentElement.style.overflow,body:document.body.style.overflow})`), oldOverflow, 'closing review restores background overflow')
  assert.deepEqual(errors, [], 'no renderer or worker errors')
  console.log(JSON.stringify({ wheel: 'passed', scrollbarDrag: 'passed', synchronized: 'passed', keyboard: 'passed', find: 'passed', searchTooltip: 'passed', gerritShortcuts: 'passed', backgroundScroll: 'passed', sessionCache: 'passed', diffPreferences: 'passed', patchSetComparison: 'passed', reviewedFlags: 'passed', compactSidebar: 'passed', renderedLines: rendered, requests: requests.requests }))
  win.destroy()
  clearTimeout(timeout)
  fs.rmSync(taskData, { recursive: true, force: true })
  app.exit(0)
}).catch((error) => { console.error(error); clearTimeout(timeout); fs.rmSync(taskData, { recursive: true, force: true }); app.exit(1) })
