import type {
  AccountInfo,
  ActionCategory,
  ActionCounts,
  ChangeInfo,
  ChangeLink,
  ChangeView,
  ReviewState,
  ReviewerStatus,
  TabId,
} from './types.ts'
import { CODE_REVIEW, READY_TO_MERGE_TAG, REVIEW_REQUESTED_KEY } from './constants.ts'

export function isBot(a: AccountInfo): boolean {
  return a.tags?.includes('SERVICE_USER') ?? false
}

export function displayName(a: AccountInfo | undefined): string {
  if (!a) return '?'
  return a.name || a.username || a.email || `#${a._account_id}`
}

/** Code-Review votes on the current patch set, keyed by account id. */
export function currentVotes(change: ChangeInfo): Map<number, number> {
  const votes = new Map<number, number>()
  for (const a of change.labels?.[CODE_REVIEW]?.all ?? []) {
    votes.set(a._account_id, a.value ?? 0)
  }
  return votes
}

export function humanReviewers(change: ChangeInfo): AccountInfo[] {
  return (change.reviewers?.REVIEWER ?? []).filter(
    (r) => !isBot(r) && r._account_id !== change.owner._account_id,
  )
}

/** Trim, lower-case and de-duplicate a team list as typed in Settings. */
export function normalizeTeam(team: string[]): string[] {
  const out: string[] = []
  for (const raw of team) {
    const t = raw.trim().toLowerCase()
    if (t && !out.includes(t)) out.push(t)
  }
  return out
}

/**
 * Team entries are usernames or email addresses, compared case-insensitively.
 * The signed-in user is always a member, so a forgotten entry never hides
 * their own vote or their review requests.
 */
export function isTeamMember(a: AccountInfo, team: string[], selfId: number): boolean {
  if (a._account_id === selfId) return true
  const keys = [a.username, a.email].filter((k): k is string => Boolean(k)).map((k) => k.toLowerCase())
  return team.some((t) => keys.includes(t))
}

export function hasTag(change: ChangeInfo, tag: string): boolean {
  return change.hashtags?.includes(tag) ?? false
}

export function requestedPatchSet(change: ChangeInfo): number | null {
  const n = parseInt(change.custom_keyed_values?.[REVIEW_REQUESTED_KEY] ?? '', 10)
  return Number.isFinite(n) && n > 0 ? n : null
}

/** Highest Code-Review vote the user may cast on this change. */
function maxPermittedVote(change: ChangeInfo): number {
  const vals = (change.permitted_labels?.[CODE_REVIEW] ?? []).map((v) => parseInt(v, 10))
  return vals.length === 0 ? 0 : Math.max(...vals)
}

/**
 * The last patch set the user reviewed: the highest one they voted or replied
 * on, from the change messages. Gerrit's own messages (new patch set, rebase,
 * ready) are tagged autogenerated and do not count, so uploading or rebasing
 * someone else's change is not a review of it.
 */
export function lastReviewedPatchSet(change: ChangeInfo, selfId: number): number | null {
  let last: number | null = null
  for (const m of change.messages ?? []) {
    if (m.author?._account_id !== selfId) continue
    if (m.tag?.startsWith('autogenerated:')) continue
    if (m._revision_number === undefined) continue
    if (last === null || m._revision_number > last) last = m._revision_number
  }
  return last
}

/**
 * What the Review button opens: the diff from the last patch set the user
 * reviewed to the current one, or the current patch set against base when
 * they never reviewed it or already reviewed this one.
 */
export function reviewLink(view: ChangeView): ChangeLink {
  const link: ChangeLink = { id: view.change._number, project: view.change.project, patchSet: view.patchSet }
  const last = view.lastReviewedPatchSet
  if (last !== null && last < view.patchSet) link.basePatchSet = last
  return link
}

/**
 * Derive the workflow state for one change.
 *
 *  in-progress    author has not asked for review of the current patch set
 *  needs-review   review requested on this patch set; someone has not voted yet
 *                 (early -1s do not change this; the last reviewer decides)
 *  needs-changes  every reviewer has voted and at least one is negative
 *  approved       every reviewer voted +1 on the current patch set
 *  ready-to-merge approved and the author tagged it for the merger, whose
 *                 +2 and submit happen together (reviewers never +2)
 *
 * WIP is not part of this. Review can happen on WIP patch sets, with
 * the WIP flag left to control when CI runs. Gerrit clears votes on a
 * new patch set, so a follow-up push the author did not re-request review for
 * drops back to in-progress instead of pinging everyone again.
 *
 * `team` (usernames or emails from Settings) limits "every reviewer" to the
 * team; an empty list means all human reviewers count.
 */
export function classify(change: ChangeInfo, selfId: number, team: string[] = []): ChangeView {
  const votes = currentVotes(change)
  const everyone: ReviewerStatus[] = humanReviewers(change).map((account) => ({
    account,
    vote: votes.get(account._account_id) ?? 0,
  }))
  // With a team, only its members decide the outcome. Everyone else is shown
  // on the change and on the External Reviews tab, but their votes are inert.
  const members = normalizeTeam(team)
  const teamScoped = members.length > 0
  const reviewers = teamScoped ? everyone.filter((r) => isTeamMember(r.account, members, selfId)) : everyone
  const externalReviewers = teamScoped ? everyone.filter((r) => !isTeamMember(r.account, members, selfId)) : []
  const pending = reviewers.filter((r) => r.vote === 0).map((r) => r.account)
  const negatives = reviewers.filter((r) => r.vote < 0)
  const isMine = change.owner._account_id === selfId
  const iAmReviewer = reviewers.some((r) => r.account._account_id === selfId)
  const myVote = votes.get(selfId) ?? 0
  const tagged = hasTag(change, READY_TO_MERGE_TAG)
  const rev = change.current_revision ? change.revisions?.[change.current_revision] : undefined
  const patchSet = rev?._number ?? 0
  const requested = requestedPatchSet(change)
  const reviewRequested = requested !== null && requested === patchSet
  const open = change.status === 'NEW'

  // The outcome is decided only when the last reviewer has voted; until then a
  // change stays under review no matter which way the early votes went.
  const everyoneVoted = reviewers.length > 0 && pending.length === 0
  let state: ReviewState
  if (change.status === 'MERGED') state = 'merged'
  else if (change.status === 'ABANDONED') state = 'abandoned'
  else if (everyoneVoted && negatives.length > 0) state = 'needs-changes'
  else if (everyoneVoted) state = tagged ? 'ready-to-merge' : 'approved'
  else if (reviewRequested) state = 'needs-review'
  else state = 'in-progress'

  return {
    change,
    state,
    reviewers,
    pending,
    externalReviewers,
    teamScoped,
    externalOwner: teamScoped && !isTeamMember(change.owner, members, selfId),
    wip: change.work_in_progress === true,
    requestedPatchSet: requested,
    reviewRequested,
    isMine,
    iAmReviewer,
    needsMyReview: open && !isMine && iAmReviewer && reviewRequested && myVote === 0,
    myVote,
    patchSet,
    patchSetCreated: rev?.created ?? change.created,
    lastReviewedPatchSet: lastReviewedPatchSet(change, selfId),
    staleReadyToMerge: open && tagged && state !== 'ready-to-merge',
    canMerge: open && maxPermittedVote(change) >= 2,
  }
}

export function classifyAll(changes: ChangeInfo[], selfId: number, team: string[] = []): ChangeView[] {
  return changes.map((c) => classify(c, selfId, team))
}

/**
 * Internal or external is decided by the owner alone, cross-referenced with
 * the team list in Settings. Who reviews does not matter, because CI and
 * maintainer lists add reviewers from outside the team to the team's own
 * changes, and those must stay on My Changes and Reviewing. Without a team
 * everything is internal.
 *
 * An internal change is listed on the five regular tabs and never on
 * External Reviews. An external change is listed on External Reviews only.
 */
export function isInternal(v: ChangeView): boolean {
  return !v.externalOwner
}

/** Open changes owned by someone outside the team: the External Reviews tab, and nowhere else. */
export function isExternalReview(v: ChangeView): boolean {
  return v.change.status === 'NEW' && v.externalOwner
}

export interface Group {
  title: string
  hint?: string
  items: ChangeView[]
}

function byState(items: ChangeView[], order: ReviewState[], titles?: Partial<Record<ReviewState, string>>): Group[] {
  return order
    .map((s) => ({ title: titles?.[s] ?? STATE_LABEL[s], items: items.filter((v) => v.state === s) }))
    .filter((g) => g.items.length > 0)
}

const REVIEWER_ORDER: ReviewState[] = ['needs-changes', 'approved', 'ready-to-merge', 'in-progress']
const REVIEWER_TITLES: Partial<Record<ReviewState, string>> = { 'in-progress': 'Author iterating, no review requested' }

/** Sections for the tabs where the user is a reviewer, the same on Reviewing and External Reviews. */
function reviewerGroups(items: ChangeView[]): Group[] {
  return [
    { title: 'Waiting on you', items: items.filter((v) => v.needsMyReview && v.state === 'needs-review') },
    { title: 'Reviewed, waiting on others', items: items.filter((v) => !v.needsMyReview && v.state === 'needs-review') },
    ...byState(items, REVIEWER_ORDER, REVIEWER_TITLES),
  ].filter((g) => g.items.length > 0)
}

/**
 * The sections of one tab, before the View filter. Every tab except External
 * Reviews lists internal changes only (see isInternal); External Reviews
 * lists the open external ones. No change is on both kinds of tab.
 */
export function groupsFor(tab: TabId, views: ChangeView[]): Group[] {
  const internal = views.filter(isInternal)
  const open = internal.filter((v) => v.change.status === 'NEW')
  switch (tab) {
    case 'needs-my-review':
      return [{ title: 'Waiting on you', items: open.filter((v) => v.needsMyReview) }].filter((g) => g.items.length > 0)
    case 'reviewing':
      return reviewerGroups(open.filter((v) => v.iAmReviewer && !v.isMine))
    case 'mine':
      return byState(
        open.filter((v) => v.isMine),
        ['needs-changes', 'approved', 'ready-to-merge', 'needs-review', 'in-progress'],
        { 'needs-review': 'Out for review', 'in-progress': 'In Progress, review not requested' },
      )
    case 'ready-to-merge':
      return [
        { title: 'Ready to Merge', items: open.filter((v) => v.state === 'ready-to-merge') },
        {
          title: 'Tagged ready-to-merge but no longer approved',
          hint: 'A new patch set reset the votes. The owner should request review again or clear the tag.',
          items: open.filter((v) => v.staleReadyToMerge),
        },
      ].filter((g) => g.items.length > 0)
    case 'merged':
      return [{ title: 'Merged in the last 14 days', items: internal.filter((v) => v.change.status === 'MERGED') }]
    case 'external-reviews':
      return reviewerGroups(views.filter(isExternalReview))
  }
}

/** The number on each tab: how many changes its sections list before the View filter. */
export function tabCounts(views: ChangeView[]): Record<TabId, number> {
  const c: Record<TabId, number> = {
    'needs-my-review': 0,
    reviewing: 0,
    mine: 0,
    'ready-to-merge': 0,
    merged: 0,
    'external-reviews': 0,
  }
  for (const v of views) {
    if (!isInternal(v)) {
      if (isExternalReview(v)) c['external-reviews']++
      continue
    }
    if (v.change.status === 'MERGED') c.merged++
    if (v.change.status !== 'NEW') continue
    if (v.needsMyReview) c['needs-my-review']++
    if (v.iAmReviewer && !v.isMine) c.reviewing++
    if (v.isMine) c.mine++
    if (v.state === 'ready-to-merge' || v.staleReadyToMerge) c['ready-to-merge']++
  }
  return c
}


export interface ActionCategoryInfo {
  id: ActionCategory
  /** Short name for the tray menu and tooltip. */
  label: string
  /** Menu bar pill color; white text passes 4.5:1 on each. */
  color: string
  /** Monochrome stand-in for the color, for the glyph badge style. */
  glyph: string
  /** Board tab that lists these changes. */
  tab: TabId
}

/** Fixed order everywhere the counts appear, so position carries meaning as well as color. */
export const ACTION_CATEGORIES: readonly ActionCategoryInfo[] = [
  { id: 'review', label: 'Needs Review', color: '#2563eb', glyph: '\u25c9', tab: 'needs-my-review' },
  { id: 'fix', label: 'Needs Changes', color: '#dc2626', glyph: '\u270e', tab: 'mine' },
  { id: 'ready', label: 'Approved', color: '#15803d', glyph: '\u25c6', tab: 'mine' },
  { id: 'merge', label: 'Ready to Merge', color: '#7c3aed', glyph: '\u21e7', tab: 'ready-to-merge' },
]

/**
 * How many changes wait on this user, by the action they need to take:
 *  review  someone on the team asked me to review the current patch set
 *  fix     my change got a negative outcome; push corrections
 *  ready   my change is approved; mark it ready to merge
 *  merge   tagged ready-to-merge and I may +2
 */
export function actionCounts(views: ChangeView[]): ActionCounts {
  const c: ActionCounts = { review: 0, fix: 0, ready: 0, merge: 0 }
  for (const v of views) {
    // Each category opens a regular tab, and those list internal changes only.
    if (v.change.status !== 'NEW' || !isInternal(v)) continue
    if (v.needsMyReview) c.review++
    if (v.isMine && v.state === 'needs-changes') c.fix++
    if (v.isMine && v.state === 'approved') c.ready++
    if (v.canMerge && v.state === 'ready-to-merge') c.merge++
  }
  return c
}

export function totalActions(c: ActionCounts): number {
  return c.review + c.fix + c.ready + c.merge
}

/** "Needs Review 3, Needs Changes 1" style summary; zero categories are left out. */
export function describeActions(c: ActionCounts): string {
  const parts = ACTION_CATEGORIES.filter((k) => c[k.id] > 0).map((k) => `${k.label} ${c[k.id]}`)
  return parts.length ? parts.join(', ') : 'Nothing waits on you'
}

/**
 * Categories to draw in the menu bar: those with something pending, plus,
 * with showZero, the ones a user always has at some point. Merge is left out
 * at zero even then, because only users with +2 rights ever get a merge
 * count, and for everyone else the pill would be a permanent zero.
 */
export function visibleCategories(c: ActionCounts, showZero = false): ActionCategoryInfo[] {
  return ACTION_CATEGORIES.filter((k) => c[k.id] > 0 || (showZero && k.id !== 'merge'))
}

/**
 * Menu bar title for the glyph style, e.g. "◉ 3  ✎ 1". Zero categories are
 * left out, so it is empty when nothing is pending, unless showZero keeps
 * them in place (merge excepted; see visibleCategories).
 */
export function glyphTitle(c: ActionCounts, showZero = false): string {
  return visibleCategories(c, showZero)
    .map((k) => `${k.glyph} ${c[k.id]}`)
    .join('  ')
}

export const STATE_LABEL: Record<ReviewState, string> = {
  'in-progress': 'In Progress',
  'needs-review': 'Needs Review',
  'needs-changes': 'Needs Changes',
  approved: 'Approved',
  'ready-to-merge': 'Ready to Merge',
  merged: 'Merged',
  abandoned: 'Abandoned',
}

function projectScope(projects: string[]): string {
  const terms = projects
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => (p.endsWith('*') ? `projects:${p.slice(0, -1)}` : `project:${p}`))
  return terms.length === 0 ? '' : ` (${terms.join(' OR ')})`
}

/**
 * Searches that together cover everything the board shows.
 *
 * Gerrit's reviewer:/reviewerin: operators exclude WIP changes (observed on
 * 3.11.2; not in the Gerrit docs), and review can happen on WIP patch sets, so
 * the second query scans open WIP changes owned by others; the caller keeps
 * only those where the user is a reviewer.
 */
export function dashboardQueries(projects: string[] = []): { direct: string; wipScan: string; merged: string } {
  return {
    direct: `is:open (owner:self OR reviewer:self OR hashtag:${READY_TO_MERGE_TAG})`,
    wipScan: `is:open is:wip -owner:self${projectScope(projects)}`,
    merged: `is:merged (owner:self OR reviewer:self) -age:14d`,
  }
}

export function isReviewer(change: ChangeInfo, accountId: number): boolean {
  return (change.reviewers?.REVIEWER ?? []).some((r) => r._account_id === accountId)
}

/**
 * Changes that share one Change-Id. Gerrit makes a separate change for each
 * branch (or project) a commit is cherry-picked to, and all of them keep the
 * Change-Id of the original commit.
 */
export interface ChangeFamily {
  /** The shared Change-Id, or the change's own id when Gerrit did not send one. */
  key: string
  /** In the order the caller gave; the first member leads the family. */
  members: ChangeView[]
}

export function familyKey(change: ChangeInfo): string {
  return change.change_id || change.id
}

/**
 * Bucket views by Change-Id without changing their order: a family sits where
 * its first member sits, and members keep their relative order. A change with
 * no cherry-picks is a family of one. Merged members stay in the family, so a
 * card can say that the change is already in on another branch.
 */
export function groupByChangeId(views: ChangeView[]): ChangeFamily[] {
  const families = new Map<string, ChangeFamily>()
  for (const v of views) {
    const key = familyKey(v.change)
    const f = families.get(key)
    if (f) f.members.push(v)
    else families.set(key, { key, members: [v] })
  }
  return [...families.values()]
}

/** Copy sorted by project, then branch, then change number: the row order inside a family card. */
export function sortByBranch(views: ChangeView[]): ChangeView[] {
  return views
    .slice()
    .sort(
      (a, b) =>
        a.change.project.localeCompare(b.change.project) ||
        a.change.branch.localeCompare(b.change.branch) ||
        a.change._number - b.change._number,
    )
}

/**
 * Urgency of a state, most urgent first. The same for the owner and for a
 * reviewer: a negative outcome needs a fix, an open request needs a look, a
 * change being iterated may need attention soon, an approved change only
 * waits for the owner to mark it, and a ready change waits on the merger.
 * Used to decide which branch of a family leads the card.
 */
export const URGENCY: readonly ReviewState[] = [
  'needs-changes',
  'needs-review',
  'in-progress',
  'approved',
  'ready-to-merge',
  'merged',
  'abandoned',
]

export function urgency(state: ReviewState): number {
  return URGENCY.indexOf(state)
}

/** Short form of a Change-Id for labels: "I3f2a91c…". */
export function shortChangeId(key: string): string {
  return key.length > 9 ? key.slice(0, 8) + '\u2026' : key
}

/** Row order inside each group. Applies to every tab. */
export type SortId = 'updated' | 'age' | 'patchset'

export const SORT_OPTIONS: { id: SortId; label: string; title: string }[] = [
  { id: 'updated', label: 'Most recent update', title: 'Changes with the newest activity first' },
  { id: 'age', label: 'Overall age, oldest first', title: 'Oldest changes first, by the date the change was created' },
  { id: 'patchset', label: 'Last patch set, oldest first', title: 'Changes whose current patch set has waited longest first, by the date it was pushed' },
]

export const DEFAULT_SORT: SortId = 'updated'

/** Return a sorted copy. Gerrit timestamps are zero-padded UTC strings, so string order is time order. */
export function sortViews(views: ChangeView[], sort: SortId): ChangeView[] {
  const byNumber = (a: ChangeView, b: ChangeView) => a.change._number - b.change._number
  return views.slice().sort((a, b) => {
    if (sort === 'age') {
      return a.change.created.localeCompare(b.change.created) || byNumber(a, b)
    }
    if (sort === 'patchset') {
      return a.patchSetCreated.localeCompare(b.patchSetCreated) || byNumber(a, b)
    }
    return b.change.updated.localeCompare(a.change.updated) || byNumber(b, a)
  })
}

/**
 * Owner groups a filter can name without picking accounts: the user's own
 * changes. Inside or outside the team is not a scope, because the tabs already
 * split on it (see groupsFor): every row on a regular tab is owned by the
 * team, and every row on External Reviews by someone else.
 */
export type AuthorScope = 'me'

export const AUTHOR_SCOPES: { id: AuthorScope; label: string; title: string }[] = [{ id: 'me', label: 'Me', title: 'Changes you own' }]

/**
 * What the View menu narrows the rows to. Authors and scopes are one
 * condition: a change passes if its owner is a picked account or falls in a
 * picked scope. The search matches the subject, or the change number exactly.
 * Rows are filtered inside each section, so the sections and their order stay.
 */
export interface ViewFilter {
  search: string
  authors: AccountInfo[]
  scopes: AuthorScope[]
}

export const EMPTY_FILTER: ViewFilter = { search: '', authors: [], scopes: [] }

export function isFilterActive(f: ViewFilter): boolean {
  return f.search.trim().length > 0 || f.authors.length > 0 || f.scopes.length > 0
}

function inScope(v: ChangeView, scope: AuthorScope): boolean {
  switch (scope) {
    case 'me':
      return v.isMine
  }
}

export function matchesFilter(v: ChangeView, f: ViewFilter): boolean {
  const q = f.search.trim().toLowerCase()
  if (q && !v.change.subject.toLowerCase().includes(q) && String(v.change._number) !== q) return false
  if (f.authors.length === 0 && f.scopes.length === 0) return true
  const owner = v.change.owner._account_id
  return f.authors.some((a) => a._account_id === owner) || f.scopes.some((s) => inScope(v, s))
}

export function filterViews(views: ChangeView[], f: ViewFilter): ChangeView[] {
  return isFilterActive(f) ? views.filter((v) => matchesFilter(v, f)) : views
}

export interface OwnerCount {
  account: AccountInfo
  count: number
}

/** The owners of these changes, most changes first, then by name: the first suggestions in the author picker. */
export function ownersOf(views: ChangeView[]): OwnerCount[] {
  const m = new Map<number, OwnerCount>()
  for (const v of views) {
    const o = v.change.owner
    const cur = m.get(o._account_id)
    if (cur) cur.count++
    else m.set(o._account_id, { account: o, count: 1 })
  }
  return [...m.values()].sort((a, b) => b.count - a.count || displayName(a.account).localeCompare(displayName(b.account)))
}

/** Case-insensitive prefix match on any word of the name, or on the username or email. */
export function accountMatches(a: AccountInfo, q: string): boolean {
  const t = q.trim().toLowerCase()
  if (!t) return true
  const words = displayName(a).toLowerCase().split(/\s+/)
  return words.some((w) => w.startsWith(t)) || (a.username?.toLowerCase().startsWith(t) ?? false) || (a.email?.toLowerCase().startsWith(t) ?? false)
}
