// Subset of Gerrit REST types used here (Gerrit 3.11 REST API, /changes/ with
// DETAILED_LABELS, DETAILED_ACCOUNTS, CURRENT_REVISION, SUBMITTABLE, SUBMIT_REQUIREMENTS).

export interface AccountInfo {
  _account_id: number
  name?: string
  email?: string
  username?: string
  /** "SERVICE_USER" marks bots (members of the Service Users group). */
  tags?: string[]
}

export interface ApprovalInfo extends AccountInfo {
  value?: number
  date?: string
}

export interface LabelInfo {
  all?: ApprovalInfo[]
  values?: Record<string, string>
  default_value?: number
}

export interface ActionInfo {
  method?: string
  label?: string
  title?: string
  /** Absent when false. */
  enabled?: boolean
}

export interface RevisionInfo {
  _number: number
  created: string
  uploader?: AccountInfo
  /** Present with CURRENT_COMMIT: the commit of this patch set, with its full message. */
  commit?: CommitInfo
  /** Present with CURRENT_ACTIONS; a key exists only if the calling user may perform it. */
  actions?: Record<string, ActionInfo>
}

export interface CommitInfo {
  subject: string
  /** The whole commit message: subject, body and the trailers at the end. */
  message: string
}

export interface ChangeMessageInfo {
  id: string
  author?: AccountInfo
  date: string
  message: string
  /** Patch set the message was posted on (a vote, a reply, an upload). */
  _revision_number?: number
  /** "autogenerated:gerrit:newPatchSet" and the like for messages Gerrit itself wrote. */
  tag?: string
}

export interface SubmitRequirementResultInfo {
  name: string
  status: 'SATISFIED' | 'UNSATISFIED' | 'OVERRIDDEN' | 'NOT_APPLICABLE' | 'ERROR' | 'FORCED'
}

export interface ChangeInfo {
  id: string
  /**
   * The Change-Id from the commit message. A cherry-pick to another branch is
   * a separate change with the same Change-Id, so the board groups on it.
   */
  change_id?: string
  _number: number
  project: string
  branch: string
  subject: string
  status: 'NEW' | 'MERGED' | 'ABANDONED'
  owner: AccountInfo
  work_in_progress?: boolean
  /** Private: visible only to the owner, the reviewers and the CCs. Absent when false. */
  is_private?: boolean
  hashtags?: string[]
  created: string
  updated: string
  submitted?: string
  submittable?: boolean
  insertions?: number
  deletions?: number
  unresolved_comment_count?: number
  labels?: Record<string, LabelInfo>
  permitted_labels?: Record<string, string[]>
  reviewers?: { REVIEWER?: AccountInfo[]; CC?: AccountInfo[]; REMOVED?: AccountInfo[] }
  current_revision?: string
  revisions?: Record<string, RevisionInfo>
  submit_requirements?: SubmitRequirementResultInfo[]
  /** Present with MESSAGES. */
  messages?: ChangeMessageInfo[]
  /** Set on the last entry of a query result when the limit cut it off. */
  _more_changes?: boolean
  /** Present with CUSTOM_KEYED_VALUES. */
  custom_keyed_values?: Record<string, string>
}

export interface SuggestedReviewerInfo {
  account?: AccountInfo
  group?: { id: string; name: string }
  count: number
}

/** Workflow state, derived purely from Gerrit data. */
export type ReviewState =
  | 'in-progress'
  | 'iterating'
  | 'needs-review'
  | 'needs-changes'
  | 'approved'
  | 'ready-to-merge'
  | 'merged'
  | 'abandoned'

export interface ReviewerStatus {
  account: AccountInfo
  /** Code-Review vote on the current patch set; 0 = not reviewed yet. */
  vote: number
  /** The username or email the `reviewer:` tag names, lower-case; set for primary reviewers only. */
  key?: string
  /**
   * Tagged as primary but not a reviewer in Gerrit: removed there, or tagged
   * by hand. `account` is then a stand-in built from the tag, with a negative
   * id, and the person is still waited for.
   */
  tagOnly?: boolean
}

export interface ChangeView {
  change: ChangeInfo
  state: ReviewState
  /**
   * The primary reviewers, whose votes decide the state: the people named by
   * a `reviewer:` hashtag, less bots and the owner. In the order Gerrit
   * lists the tags, which is alphabetical.
   */
  reviewers: ReviewerStatus[]
  /** Primary reviewers who have not voted on the current patch set. */
  pending: AccountInfo[]
  /**
   * Human reviewers on the change in Gerrit who are not tagged as primary:
   * CI-added maintainers, people from other teams, anyone who dropped in.
   * Their votes are shown but never change the state.
   */
  otherReviewers: ReviewerStatus[]
  /** A team is configured, so the owner decides between the team tabs and External Reviews. */
  teamScoped: boolean
  /** The owner is outside the configured team; the change is listed on the External Reviews tab and on no other. */
  externalOwner: boolean
  /** Gerrit WIP flag. Independent of review state; commonly used to hold CI until review is done. */
  wip: boolean
  /** Gerrit private flag: only the owner, the reviewers and the CCs can see the change. */
  isPrivate: boolean
  /** The Verified label is +1 on the current patch set (CI passed) with no -1. Required, with Active, to ask for the merge. */
  verified: boolean
  /** Patch set the author last requested review on, or null if never. */
  requestedPatchSet: number | null
  /** Every patch set the author requested review on, in the order asked. */
  requestedPatchSets: number[]
  /** The requested patch sets a primary reviewer voted on: the rounds that were answered. */
  reviewedPatchSets: number[]
  /**
   * The owner may take the request back entirely: it is the first and only
   * one, it is for the current patch set, and nobody has voted on it yet.
   */
  canWithdrawReview: boolean
  /** The request is for the current patch set, so reviews are outstanding. */
  reviewRequested: boolean
  isMine: boolean
  /** A reviewer in Gerrit, or tagged as primary. */
  iAmReviewer: boolean
  /** Tagged as primary: my vote decides, and a request lands on my Needs Review tab. */
  iAmPrimary: boolean
  needsMyReview: boolean
  myVote: number
  patchSet: number
  /** When the current patch set was pushed; the change's own date when Gerrit sent no revision. */
  patchSetCreated: string
  /**
   * Highest patch set this user voted or replied on, or null if never. A
   * review of the current patch set starts from here, so the reviewer sees
   * only what changed since they last looked.
   */
  lastReviewedPatchSet: number | null
  /** Patch set the author tagged ready-to-merge, or null: never, or an older version wrote the tag alone. */
  readyPatchSet: number | null
  /** Hashtag says ready-to-merge but it was for an earlier patch set, or the approval no longer holds. */
  staleReadyToMerge: boolean
  /**
   * Username or email from the `merger:` hashtag, lower-case: the person the
   * author asked to merge. Null when the tag is missing, which only an older
   * version of the application produces.
   */
  requestedMerger: string | null
  /** `requestedMerger` is the signed-in user. */
  mergeRequestedFromMe: boolean
  /**
   * This user may vote +2, which in this workflow is the merger's act:
   * reviewers only +1, and the merger's +2 and submit happen together.
   */
  canMerge: boolean
}

/**
 * Where in Gerrit to open a change. With a patch set, the diff view for it
 * against base; with a base patch set as well, the diff between the two.
 */
export interface ChangeLink {
  id: number
  project: string
  patchSet?: number
  basePatchSet?: number
}

/** How the macOS menu bar item shows the per-category action counts. */
export type BadgeStyle = 'color' | 'glyph'

export interface Settings {
  serverUrl: string
  username: string
  /** Colored pills, or monochrome glyphs for people who cannot tell the colors apart. */
  badgeStyle: BadgeStyle
  /** Show every category in the menu bar even when its count is zero. */
  showZeroCounts: boolean
  /**
   * Badge with the total on the app icon: macOS Dock, Linux launcher,
   * Windows taskbar overlay.
   */
  showAppBadge: boolean
  /**
   * Counts on the menu bar / tray icon (pills, glyphs, or the number in the
   * icon). Off, the tray keeps the plain icon; the tooltip and menu still
   * list the counts.
   */
  showTrayCounts: boolean
  /**
   * Optional project scope for the WIP scan (exact names, or a prefix ending
   * in "*"). Gerrit's reviewer: operator hides WIP changes, so the app has to
   * scan open WIP changes and filter client-side; on a big server, scope it.
   */
  projects: string[]
  /**
   * Usernames or email addresses of the team. The owner of a change decides
   * where it is listed: changes owned by the team are on the regular tabs
   * and on "Team Reviews", changes owned by anyone else on "External Reviews"
   * only. The signed-in user is always a member. The team has no say in the
   * state of a change; the `reviewer:` tags do (see ChangeView.reviewers).
   */
  team: string[]
  /**
   * Who the owner is offered when asking for a merge, by project. The list
   * only fills a menu: a wrong or missing entry costs one account search.
   */
  mergers: MergerRule[]
  /** Keep the compact window above other windows and on every workspace. */
  compactOnTop: boolean
}

/** The people to offer as mergers for the projects matching `project`. */
export interface MergerRule {
  /** An exact project name, a prefix ending in "*", or "*" alone for every project. */
  project: string
  /** Usernames or email addresses, lower-case. */
  people: string[]
}

export interface SettingsInput extends Settings {
  password?: string
}

export interface SettingsStatus extends Settings {
  hasPassword: boolean
  /** OS keychain encryption available for the stored password. */
  encrypted: boolean
}

export interface WindowBounds {
  x: number
  y: number
  width: number
  height: number
}

/** UI state persisted across launches (not user settings). */
export interface UiState {
  compact: boolean
  bounds?: WindowBounds
  compactBounds?: WindowBounds
}

export type TabId = 'needs-my-review' | 'reviewing' | 'mine' | 'merged' | 'team-reviews' | 'external-reviews'

/** Things that wait on the current user, one count per kind of action. */
export type ActionCategory = 'review' | 'fix' | 'ready' | 'merge'
export type ActionCounts = Record<ActionCategory, number>

/** One branch of a change in the tray menu. */
export interface ActionMenuMember {
  number: number
  branch: string
  /** Where a click goes: the diff to review, or the change page. */
  link: ChangeLink
  /** This branch needs the category's action. Otherwise it is listed greyed out with the note. */
  actionable: boolean
  /** For a branch that does not need the action: why not ("you voted +1", "in progress"). Empty otherwise. */
  note: string
}

/** A Change-Id family, or a single change, in one category of the tray menu. */
export interface ActionMenuFamily {
  subject: string
  owner: string
  /** In the family's order; at least one is actionable. */
  members: ActionMenuMember[]
}

/** What each category of the tray menu lists: one entry per card, as the counts count. */
export type ActionMenu = Record<ActionCategory, ActionMenuFamily[]>

/** What the renderer hands the tray after each refresh. */
export interface BadgePayload {
  counts: ActionCounts
  /** The changes behind the counts, for the tray menu. */
  menu: ActionMenu
  style: BadgeStyle
  showZeroCounts: boolean
  showAppBadge: boolean
  showTrayCounts: boolean
  /** Square icon with the total baked in: Windows overlay, Linux tray. */
  iconDataUrl: string
  /**
   * macOS menu bar strip of colored pills at 2x, one drawn for each menu bar
   * appearance, or null when there is nothing to draw. The main process
   * picks by the system theme, which it knows for certain.
   */
  strip: { light: TrayStrip; dark: TrayStrip } | null
}

export interface TrayStrip {
  dataUrl: string
  width: number
  height: number
}

export interface DashboardData {
  self: AccountInfo
  open: ChangeInfo[]
  merged: ChangeInfo[]
  fetchedAt: string
  /** Gerrit capped a result list; some changes may be missing. */
  truncated: boolean
}

export type ChangeAction =
  /** Owner's action. `clearTags` drops a ready-to-merge and merger tag left over from an earlier patch set. */
  | {
      type: 'requestReview'
      id: number
      patchSet: number
      /** The patch sets requested before; `patchSet` is appended to them. */
      history: number[]
      clearTags?: string[]
    }
  /**
   * Owner's action: tag the change ready-to-merge for one person, recording
   * `patchSet` as the one it is for. `merger` is a username or email; `replace` lists the merger tags already on the change,
   * which go away so that one person is named.
   */
  | { type: 'requestMerge'; id: number; merger: string; patchSet: number; replace?: string[] }
  | { type: 'withdrawReview'; id: number }
  | { type: 'setWip'; id: number; wip: boolean }
  /** Owner's action: hide the change from everyone not on it, or show it again. */
  | { type: 'setPrivate'; id: number; private: boolean }
  | { type: 'hashtag'; id: number; add?: string[]; remove?: string[] }
  /** Add to the change in Gerrit only; the person is shown but not waited for. `reviewer` is an account, group or free text. */
  | { type: 'addReviewer'; id: number; reviewer: string }
  | { type: 'removeReviewer'; id: number; accountId: number }
  /**
   * Anyone's action: add the person as a reviewer in Gerrit when they are not
   * one yet, then tag them `reviewer:<key>`. `reviewer` names one account
   * (id, username or email); a group is refused.
   */
  | { type: 'addPrimaryReviewer'; id: number; reviewer: string }
  /**
   * Anyone's action: drop the `reviewer:` tag, then try to take the person
   * off the change in Gerrit. The removal in Gerrit is best effort, because
   * only the owner (or an admin) may remove a reviewer there; the tag goes
   * either way. No `accountId` when the person is not on the change in Gerrit.
   */
  | { type: 'removePrimaryReviewer'; id: number; key: string; accountId?: number }

export type UpdateStatus = 'disabled' | 'idle' | 'checking' | 'up-to-date' | 'available' | 'downloading' | 'downloaded' | 'error'

/** What the updater knows, pushed to the UI and the tray after every change. */
export interface UpdateState {
  status: UpdateStatus
  currentVersion: string
  /** Newest GitHub release when it is newer than the running version. */
  availableVersion: string | null
  /** Version whose installer is on disk, waiting for a restart. */
  downloadedVersion: string | null
  /** Release notes as plain text lines, from the GitHub release. */
  releaseNotes: string | null
  releaseUrl: string | null
  downloadPercent: number | null
  checkedAt: string | null
  /** Why the last step failed, or why updates are off. */
  message: string | null
  errorContext: 'check' | 'download' | 'install' | null
}
