// Subset of Gerrit REST types used here (Gerrit 3.11 REST API, /changes/ with
// DETAILED_LABELS, DETAILED_ACCOUNTS, CURRENT_REVISION, SUBMITTABLE, SUBMIT_REQUIREMENTS).

export interface AccountInfo {
  _account_id: number
  name?: string
  email?: string
  username?: string
  /** "SERVICE_USER" marks bots (members of the Service Users group). */
  tags?: string[]
}

export interface ApprovalInfo extends AccountInfo {
  value?: number
  date?: string
}

export interface LabelInfo {
  all?: ApprovalInfo[]
  values?: Record<string, string>
  default_value?: number
}

export interface ActionInfo {
  method?: string
  label?: string
  title?: string
  /** Absent when false. */
  enabled?: boolean
}

export interface RevisionInfo {
  _number: number
  created: string
  uploader?: AccountInfo
  /** Present with CURRENT_ACTIONS; a key exists only if the calling user may perform it. */
  actions?: Record<string, ActionInfo>
}

export interface ChangeMessageInfo {
  id: string
  author?: AccountInfo
  date: string
  message: string
  /** Patch set the message was posted on (a vote, a reply, an upload). */
  _revision_number?: number
  /** "autogenerated:gerrit:newPatchSet" and the like for messages Gerrit itself wrote. */
  tag?: string
}

export interface SubmitRequirementResultInfo {
  name: string
  status: 'SATISFIED' | 'UNSATISFIED' | 'OVERRIDDEN' | 'NOT_APPLICABLE' | 'ERROR' | 'FORCED'
}

export interface ChangeInfo {
  id: string
  /**
   * The Change-Id from the commit message. A cherry-pick to another branch is
   * a separate change with the same Change-Id, so the board groups on it.
   */
  change_id?: string
  _number: number
  project: string
  branch: string
  subject: string
  status: 'NEW' | 'MERGED' | 'ABANDONED'
  owner: AccountInfo
  work_in_progress?: boolean
  hashtags?: string[]
  created: string
  updated: string
  submitted?: string
  submittable?: boolean
  insertions?: number
  deletions?: number
  unresolved_comment_count?: number
  labels?: Record<string, LabelInfo>
  permitted_labels?: Record<string, string[]>
  reviewers?: { REVIEWER?: AccountInfo[]; CC?: AccountInfo[]; REMOVED?: AccountInfo[] }
  current_revision?: string
  revisions?: Record<string, RevisionInfo>
  submit_requirements?: SubmitRequirementResultInfo[]
  /** Present with MESSAGES. */
  messages?: ChangeMessageInfo[]
  /** Set on the last entry of a query result when the limit cut it off. */
  _more_changes?: boolean
  /** Present with CUSTOM_KEYED_VALUES. */
  custom_keyed_values?: Record<string, string>
}

export interface SuggestedReviewerInfo {
  account?: AccountInfo
  group?: { id: string; name: string }
  count: number
}

/** Workflow state, derived purely from Gerrit data. */
export type ReviewState =
  | 'in-progress'
  | 'needs-review'
  | 'needs-changes'
  | 'approved'
  | 'ready-to-merge'
  | 'merged'
  | 'abandoned'

export interface ReviewerStatus {
  account: AccountInfo
  /** Code-Review vote on the current patch set; 0 = not reviewed yet. */
  vote: number
}

export interface ChangeView {
  change: ChangeInfo
  state: ReviewState
  /**
   * The reviewers whose votes decide the state: humans, not the owner, and
   * when a team is configured, only its members.
   */
  reviewers: ReviewerStatus[]
  /** Reviewers who have not voted on the current patch set. */
  pending: AccountInfo[]
  /**
   * Human reviewers outside the configured team. Their votes are shown but
   * never change the state, and they do not make the change external; only
   * the owner does. Empty when no team is configured.
   */
  externalReviewers: ReviewerStatus[]
  /** A team is configured, so `reviewers` is limited to its members. */
  teamScoped: boolean
  /** The owner is outside the configured team; the change belongs on the External Reviews tab. */
  externalOwner: boolean
  /** Gerrit WIP flag. Independent of review state; commonly used to hold CI until review is done. */
  wip: boolean
  /** Patch set the author last requested review on, or null if never. */
  requestedPatchSet: number | null
  /** The request is for the current patch set, so reviews are outstanding. */
  reviewRequested: boolean
  isMine: boolean
  iAmReviewer: boolean
  needsMyReview: boolean
  myVote: number
  patchSet: number
  /** When the current patch set was pushed; the change's own date when Gerrit sent no revision. */
  patchSetCreated: string
  /**
   * Highest patch set this user voted or replied on, or null if never. A
   * review of the current patch set starts from here, so the reviewer sees
   * only what changed since they last looked.
   */
  lastReviewedPatchSet: number | null
  /** Hashtag says ready-to-merge but the approval no longer holds (e.g. new patch set). */
  staleReadyToMerge: boolean
  /**
   * This user may vote +2, which in this workflow is the merger's act:
   * reviewers only +1, and the merger's +2 and submit happen together.
   */
  canMerge: boolean
}

/**
 * Where in Gerrit to open a change. With a patch set, the diff view for it
 * against base; with a base patch set as well, the diff between the two.
 */
export interface ChangeLink {
  id: number
  project: string
  patchSet?: number
  basePatchSet?: number
}

/** How the macOS menu bar item shows the per-category action counts. */
export type BadgeStyle = 'color' | 'glyph'

export interface Settings {
  serverUrl: string
  username: string
  /** Colored pills, or monochrome glyphs for people who cannot tell the colors apart. */
  badgeStyle: BadgeStyle
  /** Show every category in the menu bar even when its count is zero. */
  showZeroCounts: boolean
  /**
   * Badge with the total on the app icon: macOS Dock, Linux launcher,
   * Windows taskbar overlay.
   */
  showAppBadge: boolean
  /**
   * Counts on the menu bar / tray icon (pills, glyphs, or the number in the
   * icon). Off, the tray keeps the plain icon; the tooltip and menu still
   * list the counts.
   */
  showTrayCounts: boolean
  /**
   * Optional project scope for the WIP scan (exact names, or a prefix ending
   * in "*"). Gerrit's reviewer: operator hides WIP changes, so the app has to
   * scan open WIP changes and filter client-side; on a big server, scope it.
   */
  projects: string[]
  /**
   * Usernames or email addresses of the people whose votes decide the state
   * of a change. Empty means every reviewer counts. The signed-in user is
   * always a member. Votes from reviewers outside the team never change the
   * state. Changes owned outside the team appear on the "External Reviews" tab.
   */
  team: string[]
  /** Keep the compact window above other windows and on every workspace. */
  compactOnTop: boolean
}

export interface SettingsInput extends Settings {
  password?: string
}

export interface SettingsStatus extends Settings {
  hasPassword: boolean
  /** OS keychain encryption available for the stored password. */
  encrypted: boolean
}

export interface WindowBounds {
  x: number
  y: number
  width: number
  height: number
}

/** UI state persisted across launches (not user settings). */
export interface UiState {
  compact: boolean
  bounds?: WindowBounds
  compactBounds?: WindowBounds
}

export type TabId = 'needs-my-review' | 'reviewing' | 'mine' | 'ready-to-merge' | 'merged' | 'external-reviews'

/** Things that wait on the current user, one count per kind of action. */
export type ActionCategory = 'review' | 'fix' | 'ready' | 'merge'
export type ActionCounts = Record<ActionCategory, number>

/** What the renderer hands the tray after each refresh. */
export interface BadgePayload {
  counts: ActionCounts
  style: BadgeStyle
  showZeroCounts: boolean
  showAppBadge: boolean
  showTrayCounts: boolean
  /** Square icon with the total baked in: Windows overlay, Linux tray. */
  iconDataUrl: string
  /** macOS menu bar strip of colored pills at 2x, or null when there is nothing to draw. */
  strip: { dataUrl: string; width: number; height: number } | null
}

export interface DashboardData {
  self: AccountInfo
  open: ChangeInfo[]
  merged: ChangeInfo[]
  fetchedAt: string
  /** Gerrit capped a result list; some changes may be missing. */
  truncated: boolean
}

export type ChangeAction =
  | { type: 'requestReview'; id: number; patchSet: number }
  | { type: 'withdrawReview'; id: number }
  | { type: 'setWip'; id: number; wip: boolean }
  /** Merger's action: vote +2 on the current patch set, then submit. */
  | { type: 'merge'; id: number }
  | { type: 'hashtag'; id: number; add?: string[]; remove?: string[] }
  | { type: 'addReviewer'; id: number; reviewer: string }
  | { type: 'removeReviewer'; id: number; accountId: number }

export type UpdateStatus = 'disabled' | 'idle' | 'checking' | 'up-to-date' | 'available' | 'downloading' | 'downloaded' | 'error'

/** What the updater knows, pushed to the UI and the tray after every change. */
export interface UpdateState {
  status: UpdateStatus
  currentVersion: string
  /** Newest GitHub release when it is newer than the running version. */
  availableVersion: string | null
  /** Version whose installer is on disk, waiting for a restart. */
  downloadedVersion: string | null
  /** Release notes as plain text lines, from the GitHub release. */
  releaseNotes: string | null
  releaseUrl: string | null
  downloadPercent: number | null
  checkedAt: string | null
  /** Why the last step failed, or why updates are off. */
  message: string | null
  errorContext: 'check' | 'download' | 'install' | null
}
